Repository GameBoiss/ask-me, pull requests merged in 2023-03, with the labels that each got.

#1 Create pull request template for future PR's
  .github/pull_request.md
Labels: Final-Review

#2 fixed PR temp path
  ask-me-gpt/.github/pull_request.md
Labels: Final-Review

#8 explained how to run lint and lint fix
  README.md
Labels: Final-Review

#9 fixed read me
  README.md
Labels: Final-Review

#13 Readme update
  README.md
Labels: Final-Review

#15 cypress addition
  .eslintrc.json
  cypress.config.ts
  cypress/e2e/spec.cy.ts
  cypress/support/commands.ts
  cypress/support/e2e.ts
  package-lock.json
  package.json
Labels: enhancement

#17 Fix undefined errors in jest/cypress specs
  .eslintrc.json
  __tests__/index.test.jsx
  __tests__/index.test.tsx
  cypress.config.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: bug
